services:

  mariadb:
    image: mariadb:latest
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./workspace/mariadb:/var/lib/mysql
      - ./my.server.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf
    restart: unless-stopped

  frankenphp:
    build: .
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./workspace/root:/root
      - ./workspace/app:/app
      - ./Caddyfile.d:/etc/frankenphp/Caddyfile.d
    networks:
      default:
        aliases:
          - office.localhost
    depends_on:
      - mariadb
    restart: unless-stopped
